/* UI regression checks; inject model fixtures to avoid rerunning GPU inference.
   CLAIMGUARD_URL=http://127.0.0.1:8517 PLAYWRIGHT_MODULE=... node tests/test_claims_ui.cjs */
const assert = require('assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==';
const result = {name:'first.png',url:png,artifacts:{heatmap:png},complete:true,score:.68,threshold:.75,route:'AOS',scores:{trufor:.8,fused:.7,recapture:.3},models:Object.fromEntries(['trufor','fused','recapture'].map((model,i)=>[model,{model,score:[.8,.7,.3][i],elapsed_sec:1,status:'complete'}]))};
(async()=>{
  const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.addInitScript(legacy=>{if(!localStorage.getItem('cg-real-claims-v1'))localStorage.setItem('cg-real-claims-v1',JSON.stringify([legacy]))}, {id:'LEGACY',date:'2026-09-18',amount:10,status:'심사완료',images:[{...result,url:undefined,artifacts:{}}]});
    async function load(){
      await page.goto(process.env.CLAIMGUARD_URL||'http://127.0.0.1:8517');
      await page.waitForSelector('iframe');
      const frame=await (await page.$('iframe')).contentFrame();
      await frame.waitForFunction(()=>document.querySelector('.system-state')?.textContent.includes('연결됨'));
      await frame.evaluate(()=>claimsReady);
      return frame;
    }
    let frame=await load();
    assert.deepEqual(await frame.$$eval('.nav-btn[data-process]',buttons=>buttons.map(button=>[button.dataset.process,button.querySelector('b').textContent])),[['1','고객'],['2','내부 프로세스'],['3','보험사 직원']]);
    assert.equal(await frame.$eval('.nav-btn[data-process="1"]',button=>button.classList.contains('active')),true);
    assert.equal(await frame.$$eval('#analysisView #roiSettingsBtn',buttons=>buttons.length),0,'ROI control is removed from customer analysis');
    assert.equal(await frame.evaluate(()=>{setFiles([new File(['a'],'one.png',{type:'image/png'})],{append:true});setFiles([new File(['b'],'two.png',{type:'image/png'})],{append:true});return files.length}),2,'Repeated single-file additions accumulate');
    assert.equal(await frame.$$eval('#fileList [data-remove-file]',buttons=>buttons.length),2);
    await frame.click('#fileList [data-remove-file="0"]');
    assert.deepEqual(await frame.evaluate(()=>[files.length,files[0].name]),[1,'two.png']);
    assert.equal(await frame.$eval('#fileSummary',el=>el.textContent),'이미지 1장이 첨부되었습니다.');
    await frame.evaluate(()=>setFiles([new File(['a'],'one.png',{type:'image/png'})],{append:true}));
    assert.equal(await frame.evaluate(()=>{setFiles(Array.from({length:18},(_,i)=>new File(['x'],`extra-${i}.png`,{type:'image/png'})),{append:true});return files.length}),20,'Twenty images are accepted');
    assert.equal(await frame.$eval('#fileSummary',el=>el.textContent),'이미지 20장이 첨부되었습니다.');
    assert.equal(await frame.$eval('#fileList',el=>getComputedStyle(el).overflowY),'auto','Attached image list scrolls internally');
    assert.deepEqual(await frame.evaluate(()=>{const before=files.length;setFiles([new File(['x'],'too-many.png',{type:'image/png'})],{append:true});return [before,files.length]}),[20,20],'Rejected additions preserve existing files');
    await frame.evaluate(()=>setFiles([]));
    assert.equal(await frame.$$eval('[data-overlay="mask"]',els=>els.length),0);
    assert.equal(await frame.evaluate(()=>claims.length),1,'Legacy migration');
    assert.equal(await frame.evaluate(()=>claims[0].status),'심사대기','Legacy automatic completion is reopened');
    await frame.click('[data-view="claims"]');
    assert.equal(await frame.$eval('.nav-btn[data-process="3"]',button=>button.classList.contains('active')),true);
    assert.equal(await frame.$$eval('#claimsView #roiSettingsBtn',buttons=>buttons.length),1,'ROI control belongs to the reviewer console');
    await frame.click('#roiSettingsBtn');
    assert.equal(await frame.$eval('#roiSettingsView',view=>view.classList.contains('active')),true);
    assert.equal(await frame.$eval('.nav-btn[data-process="3"]',button=>button.classList.contains('active')),true);
    await frame.click('#backRoiBtn');
    assert.equal(await frame.$eval('#claimsView',view=>view.classList.contains('active')),true);
    assert.equal(await frame.$$eval('[data-filter="incomplete"]',els=>els.length),0,'Incomplete filter is removed');
    assert.match(await frame.$eval('.table-head',el=>el.textContent),/분석 신호/);
    assert.match(await frame.$eval('.table-head',el=>el.textContent),/점검결과/);
    assert.doesNotMatch(await frame.$eval('#kpis',el=>el.textContent),/심사 완료/);
    await frame.click('[data-open-claim="LEGACY"]');
    assert.match(await frame.$eval('#claimDetail',el=>el.textContent),/저장된 이미지가 없습니다/);
    assert.equal(await frame.$$eval('#deleteDetailClaimBtn',els=>els.length),1,'Temporary claim deletion control is available');
    assert.deepEqual(await frame.$eval('#deleteDetailClaimBtn',el=>{const style=getComputedStyle(el);return [style.position,style.right,style.bottom,style.opacity]}),['fixed','0px','0px','0'],'Claim deletion control is an invisible bottom-right hit area');
    assert.equal(await frame.$$eval('[data-delete-image]',els=>els.length),0,'Individual image deletion remains unavailable');
    await frame.evaluate(async()=>{await claimStore.remove('LEGACY');claims=[]});
    frame=await load();
    assert.equal(await frame.evaluate(()=>claims.length),0,'Deleted legacy must not migrate again');
    for(const id of ['customerName','customerBirth','customerPhone','accidentDate','accidentCause'])assert.equal(await frame.$$eval(`#${id}`,els=>els.length),1,id);
    assert.match(await frame.evaluate(()=>generateClaimId()),/^MLM-\d{4}-\d{6}$/);
    assert.equal(await frame.evaluate(()=>Array.from({length:100},generateClaimAmount).every(value=>value>=500000&&value<=2000000&&value%100===0)),true,'Generated claim amounts use the configured range and 100-won units');
    await frame.evaluate(async fixture=>{
      const records=Array.from({length:12},(_,index)=>({id:`PAG-${String(index+1).padStart(2,'0')}`,date:`2026-09-${String(index+1).padStart(2,'0')}`,amount:(index+1)*1000,status:'심사대기',images:[{...fixture,name:`page-${index+1}.png`,score:(index+1)/20}]}));
      for(const record of records)await claimStore.put(record);
      claims=records;showView('claims');
    },result);
    assert.equal(await frame.$$eval('#claimRows .claim-row',rows=>rows.length),10,'Ten claims per page');
    assert.match(await frame.$eval('#claimPagination',el=>el.textContent),/1\/2페이지/);
    assert.equal(await frame.$$eval('#sortSelect',els=>els.length),0,'Toolbar sort menu is removed');
    assert.doesNotMatch(await frame.$eval('.table-head',el=>el.textContent),/관리/);
    assert.equal(await frame.$$eval('#claimRows [data-delete-claim]',els=>els.length),0,'List delete controls are removed');
    assert.equal(await frame.$$eval('.claim-id small',els=>els.length),0,'Amount is separated from claim number');
    await frame.click('[data-page="next"]');
    assert.equal(await frame.$$eval('#claimRows .claim-row',rows=>rows.length),2,'Remaining claims appear on the next page');
    await frame.click('[data-sort="amount"]');
    assert.match(await frame.$eval('#claimRows .claim-id',el=>el.textContent),/PAG-01/,'Amount ascending sort');
    await frame.click('[data-sort="amount"]');
    assert.match(await frame.$eval('#claimRows .claim-id',el=>el.textContent),/PAG-12/,'Amount descending sort');
    await frame.evaluate(async()=>{for(const claim of claims)await claimStore.remove(claim.id);claims=[];claimPage=1;renderClaims()});
    await frame.evaluate(results=>{requestId='test-batch';analysisResults=results;document.querySelector('#claimId').value='MLM-TEST-PHOTOS';document.querySelector('#customerName').value='홍길동';document.querySelector('#customerBirth').value='1990-01-01';document.querySelector('#customerPhone').value='010-1234-5678';document.querySelector('#accidentDate').value='2026-09-17';document.querySelector('#accidentCause').value='주차장에서 후진 중 기둥에 좌측 범퍼를 충돌함';pendingClaimInfo=customerFormData();selectResult(0)},[result,{...result,name:'second.png'}]);
    assert.equal(await frame.$eval('#resultPosition',el=>el.textContent),'1 / 2');
    assert.equal(await frame.$eval('#previousResultBtn',el=>el.disabled),true);
    await frame.click('#nextResultBtn');
    assert.equal(await frame.$eval('#resultPicker',el=>el.value),'1');
    assert.equal(await frame.$eval('#resultPosition',el=>el.textContent),'2 / 2');
    assert.equal(await frame.$eval('#nextResultBtn',el=>el.disabled),true);
    await frame.click('#previousResultBtn');
    assert.equal(await frame.$eval('#resultPicker',el=>el.value),'0');
    await frame.click('#saveBtn');
    await frame.waitForSelector('#claimsView.active');
    assert.match(await frame.$eval('#kpis',el=>el.textContent),/검토대상1/);
    assert.equal(await frame.evaluate(()=>claimCategory(claims[0])),'review','Highest model score drives claim risk');
    assert.equal(await frame.evaluate(()=>claims[0].status),'심사대기');
    assert.deepEqual(await frame.evaluate(()=>[claims[0].customerName,claims[0].customerPhone,claims[0].accidentCause]),['홍길동','010-1234-5678','주차장에서 후진 중 기둥에 좌측 범퍼를 충돌함']);
    assert.equal(await frame.$eval('.analysis-signal.review',el=>el.textContent),'검토대상');
    assert.equal(await frame.$eval('#claimRows .risk',el=>el.textContent),'80.0%');
    frame=await load();
    await frame.click('[data-view="claims"]');
    await frame.click('[data-filter="review"]');
    await frame.click('[data-open-claim="MLM-TEST-PHOTOS"]');
    assert.match(await frame.$eval('#claimDetail',el=>el.textContent),/주차장에서 후진 중 기둥에 좌측 범퍼를 충돌함/);
    assert.equal(await frame.$$eval('#inspectionControls button',buttons=>buttons.map(button=>button.textContent).join(',')),'승인,반송');
    await frame.click('#inspectionControls [data-inspection="approved"]');
    await frame.waitForFunction(()=>claims[0].inspectionResult==='approved');
    assert.equal(await frame.$eval('#claimDetailView',view=>view.classList.contains('active')),true);
    assert.equal(await frame.$eval('#inspectionCompletionModal',modal=>modal.hidden),false);
    assert.equal(await frame.$eval('#inspectionCompletionTitle',el=>el.textContent),'다음 심사단계 진행');
    assert.equal(await frame.$$eval('#inspectionCompletionMessage,#completionNextBtn',els=>els.length),0);
    assert.equal(await frame.$eval('#completionBackBtn',el=>el.textContent),'목록으로 돌아가기');
    await frame.click('#completionBackBtn');
    assert.equal(await frame.$eval('#claimsView',view=>view.classList.contains('active')),true);
    assert.equal(await frame.$eval('#claimRows .inspection-result',el=>el.textContent),'승인');
    await frame.click('[data-open-claim="MLM-TEST-PHOTOS"]');
    await frame.click('#inspectionControls [data-inspection="returned"]');
    await frame.waitForFunction(()=>claims[0].inspectionResult==='returned');
    assert.equal(await frame.$eval('#inspectionCompletionTitle',el=>el.textContent),'추가 반송절차 진행');
    assert.equal(await frame.$$eval('#inspectionCompletionMessage,#completionNextBtn',els=>els.length),0);
    await frame.click('#completionBackBtn');
    await frame.click('[data-open-claim="MLM-TEST-PHOTOS"]');
    await frame.waitForFunction(()=>[...document.querySelectorAll('.photo-card img')].length===2&&[...document.querySelectorAll('.photo-card img')].every(img=>img.complete&&img.naturalWidth>0));
    assert.equal(await frame.$$eval('.photo-card .analysis-signal.review',els=>els.length),2);
    assert.deepEqual(await frame.$$eval('.photo-card .risk',els=>els.map(el=>el.textContent)),['80.0%','80.0%']);
    await frame.click('.photo-card[data-index="1"]');
    const detail=await frame.$eval('#imageDetail',el=>el.textContent);
    for(const text of ['second.png','원본 이미지','의심 영역','TruFor','FUSED','Recapture','통합 점수','최고 신호 · TruFor','80.0%','75.0%','80.0% ≥ 75.0%','검토대상','주차장에서 후진 중 기둥에 좌측 범퍼를 충돌함'])assert.ok(detail.includes(text),text);
    await frame.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{source:window.parent,data:{type:'streamlit:render',args:{threshold:.83}}})));
    assert.equal(await frame.$eval('#imageDetail .threshold-line b',el=>el.textContent),'75.0%','Current ROI changes must not overwrite the analysis-time threshold');
    assert.match(await frame.$eval('#imageDetail .saved-comparison',el=>el.textContent),/80.0% ≥ 75.0%/);
    assert.equal(await frame.$$eval('#imageDetail img',els=>els.length),2);
    assert.equal(await frame.$$eval('#completeReviewBtn',els=>els.length),0,'Review completion button is removed');
    await frame.click('#backImageClaimBtn');
    assert.equal(await frame.$$eval('#deleteDetailClaimBtn',els=>els.length),1,'Temporary claim deletion control remains available');
    assert.equal(await frame.$$eval('[data-delete-image]',els=>els.length),0,'Individual image deletion remains unavailable');
    await frame.evaluate(async()=>{for(const claim of claims)await claimStore.remove(claim.id);claims=[];showView('analysis')});
    // Storage failures must not create phantom claims.
    await frame.evaluate(r=>{goHome();requestId='failed-save';analysisResults=[r];selectResult(0);claimStore.put=async()=>{throw new Error('quota')}},result);
    await frame.click('#saveBtn');
    await frame.waitForFunction(()=>document.querySelector('#toast').textContent.includes('저장하지 못했습니다'));
    assert.equal(await frame.evaluate(()=>claims.length),0);
    assert.equal(await frame.$eval('#saveBtn',el=>el.disabled),false);
    assert.deepEqual(errors,[]);
    console.log('PASS: migration, Mask removal, image persistence, detail evidence, historical threshold, deletion controls removed, and failed-save handling');
  } finally {await browser.close()}
})().catch(error=>{console.error(error);process.exit(1)});
